AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  demo-app

  Sample SAM Template for demo-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  MailgunNotificationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          SNStopic: !Ref MySnsTopic
      Policies:
        - S3FullAccessPolicy:
            BucketName: ayubs3bucket # bucket name without arn
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt MySnsTopic.TopicName
      Events:
        MailgunNotify:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /MailgunPost
            Method: post  
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        External:
        - 'aws-sdk'
        # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints: 
        - app.ts
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: ayubs3bucket
  MySnsTopic:
    Type: AWS::SNS::Topic
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MailgunNotificationFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for Mailgun Notification Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  MailgunNotificationFunction:
    Description: "Mailgun Notification Lambda Function ARN"
    Value: !GetAtt MailgunNotificationFunction.Arn
  S3Bucket:
    Description: "S3 Bucket ARN"
    Value: !GetAtt S3Bucket.Arn
  MailgunNotificationFunctionIamRole:
    Description: "Implicit IAM Role created for Mailgun Notification Function"
    Value: !GetAtt MailgunNotificationFunctionRole.Arn
  SNStopicName:
    Description: SNS topic name
    Value: !GetAtt MySnsTopic.TopicName
  SNStopicARN:
    Description: SNS topic ARN
    Value: !Ref MySnsTopic
